<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbo_Dropdown</name>
   <tag></tag>
   <elementGuidId>0f4f144c-d62c-480b-80de-1eb1867ede2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select#dropdown</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
